In [1]:
from pymanopt.manifolds import Grassmann, ComplexGrassmann
import numpy as np
from compute_centroid import *
from grass_DR import *
from PNG import *
from sklearn.decomposition import PCA
from PGA import *

# Example 1: 15 points on Gr(2, 6) embedded in Gr(2, 10) 

## Generate data

In [2]:
m = 6
n = 10
p = 2
N = 15
sig = 0.1
gr_low = Grassmann(m, p, N)
gr = Grassmann(n, p, N)
gr_map = Grassmann(n, m)

X_low = gr_low.rand() # N x m x p
A = gr_map.rand() # n x m
#B = np.random.normal(0, 0.1, (n, p)) # n x p
B = np.zeros((n,p))
AAT = np.matmul(A, A.T) 
IAATB = np.matmul(np.eye(n) - AAT, B)
X = np.array([np.linalg.qr(np.matmul(A, X_low[i]) + IAATB)[0] for i in range(N)]) # N x n x p
X = gr.exp(X, sig * gr.randvec(X)) # perturb the emdedded X

## Compute the score using PNG and apply PCA to the scores

In [3]:
scores = PNG(X)

n_c = 5
pca = PCA(n_components = n_c)
pca.fit(scores)
print(f'The ratios of expressed variance first {n_c} PCs.')
print(pca.explained_variance_ratio_.round(2))
print(f'The cumulative ratios of expressed variance first {n_c} PCs.')
print(np.cumsum(pca.explained_variance_ratio_).round(2))

Gr(2, 10) -> Gr(2, 9)
Gr(2, 9) -> Gr(2, 8)
Gr(2, 8) -> Gr(2, 7)
Gr(2, 7) -> Gr(2, 6)
Gr(2, 6) -> Gr(2, 5)
Gr(2, 5) -> Gr(2, 4)
Gr(2, 4) -> Gr(2, 3)
Gr(2, 3) -> Gr(1, 3)
Gr(1, 3) -> Gr(1, 2)
Gr(1, 2) -> NGM
The ratios of expressed variance first 5 PCs.
[0.43 0.2  0.16 0.09 0.06]
The cumulative ratios of expressed variance first 5 PCs.
[0.43 0.63 0.78 0.87 0.93]


# Example 2: 15 points on Gr(2, $C^6$) embedded in Gr(2, $C^{10}$) 

## Generate data

In [4]:
m = 4
n = 5
p = 2
N = 15
sig = 0.1
cgr_low = ComplexGrassmann(m, p, N)
cgr = ComplexGrassmann(n, p, N)
cgr_map = ComplexGrassmann(n, m)

X_low = cgr_low.rand() # N x m x p
A = cgr_map.rand() # n x m
#B = np.random.normal(0, 0.1, (n, p)) # n x p
B = np.zeros((n,p))
AAT = np.matmul(A, A.conj().T) 
IAATB = np.matmul(np.eye(n) - AAT, B)
X = np.array([np.linalg.qr(np.matmul(A, X_low[i]) + IAATB)[0] for i in range(N)]) # N x n x p
X = cgr.exp(X, sig * cgr.randvec(X)) # perturb the emdedded X

In [5]:
scores = PNG(X)

Gr(2, 5) -> Gr(2, 4)
Gr(2, 4) -> Gr(2, 3)
Gr(2, 3) -> Gr(1, 3)
Gr(1, 3) -> Gr(1, 2)
Gr(1, 2) -> NGM


In [6]:
n_c = 5
pca = PCA(n_components = n_c)
pca.fit(np.hstack((scores.real, scores.imag)))
print(f'The ratios of expressed variance first {n_c} PCs.')
print(pca.explained_variance_ratio_.round(2))
print(f'The cumulative ratios of expressed variance first {n_c} PCs.')
print(np.cumsum(pca.explained_variance_ratio_).round(2))

The ratios of expressed variance first 5 PCs.
[0.34 0.24 0.18 0.11 0.08]
The cumulative ratios of expressed variance first 5 PCs.
[0.34 0.57 0.75 0.86 0.94]
