In [1]:
from pymanopt.manifolds import Grassmann, ComplexGrassmann, SpecialOrthogonalGroup, Euclidean
import numpy as np
from compute_centroid import *
from grass_DR import *
from PNG import *
from sklearn.decomposition import PCA
from PGA import *
from Complex_PCA import *
import matplotlib.pyplot as plt

# Example 1: 15 points on Gr(2, 6) embedded in Gr(2, 10) 

## Generate data

In [9]:
m = 4
n = 10
p = 1
N = 10
sig = 0
gr_low = Grassmann(m, p, N)
gr = Grassmann(n, p, N)
gr_map = Grassmann(n, m)

X_low = gr_low.rand() # N x m x p
A = gr_map.rand() # n x m
#B = np.random.normal(0, 0.1, (n, p)) # n x p
B = np.zeros((n,p))
AAT = np.matmul(A, A.T) 
IAATB = np.matmul(np.eye(n) - AAT, B)
X = np.array([np.linalg.qr(np.matmul(A, X_low[i]) + IAATB)[0] for i in range(N)]) # N x n x p
X = gr.exp(X, sig * gr.randvec(X)) # perturb the emdedded X

## Compute the score using PNG and apply PCA to the scores

In [10]:
scores_PNG = PNG(X, verbosity = 1)

Gr(1, 10) -> Gr(1, 9)
Terminated - min grad norm reached after 216 iterations, 0.86 seconds.

Gr(1, 9) -> Gr(1, 8)
Terminated - min grad norm reached after 187 iterations, 0.72 seconds.

Gr(1, 8) -> Gr(1, 7)
Terminated - min grad norm reached after 146 iterations, 0.56 seconds.

Gr(1, 7) -> Gr(1, 6)
Terminated - min grad norm reached after 143 iterations, 0.55 seconds.

Gr(1, 6) -> Gr(1, 5)
Terminated - min grad norm reached after 138 iterations, 0.53 seconds.

Gr(1, 5) -> Gr(1, 4)
Terminated - min grad norm reached after 192 iterations, 0.71 seconds.

Gr(1, 4) -> Gr(1, 3)
Terminated - min grad norm reached after 67 iterations, 0.26 seconds.

Gr(1, 3) -> Gr(1, 2)
Terminated - min grad norm reached after 20 iterations, 0.11 seconds.

Gr(1, 2) -> NGM


In [11]:
n_c = 4
pca = PCA(n_components = n_c)
pca.fit(scores_PNG)
print(f'The ratios of expressed variance of the first {n_c} PCs.')
print(pca.explained_variance_ratio_.round(2))
print(f'The cumulative ratios of expressed variance of the first {n_c} PCs.')
print(np.cumsum(pca.explained_variance_ratio_).round(2))

The ratios of expressed variance of the first 4 PCs.
[0.73 0.25 0.02 0.  ]
The cumulative ratios of expressed variance of the first 4 PCs.
[0.73 0.98 1.   1.  ]


## PGA

In [12]:
gr = Grassmann(n, p)
n_c = 5
pga = PGA(X, n_c, gr)

print(f'The ratios of expressed variance of the first {n_c} PCs.')
print(pga.explained_variance_ratio_.round(2))
print(f'The cumulative ratios of expressed variance of the first {n_c} PCs.')
print(np.cumsum(pga.explained_variance_ratio_).round(2))

The ratios of expressed variance of the first 5 PCs.
[0.49 0.36 0.15 0.   0.  ]
The cumulative ratios of expressed variance of the first 5 PCs.
[0.49 0.85 1.   1.   1.  ]


# Example 2: 15 points on Gr(2, $C^4$) embedded in Gr(2, $C^5$) 

## Generate data

In [23]:
m = 5
n = 12
p = 1
N = 30
sig = 0.01
cgr_low = ComplexGrassmann(m, p, N)
cgr = ComplexGrassmann(n, p, N)
cgr_map = ComplexGrassmann(n, m)

X_low = cgr_low.rand() # N x m x p
A = cgr_map.rand() # n x m
#B = np.random.normal(0, 0.1, (n, p)) # n x p
B = np.zeros((n,p))
AAT = np.matmul(A, A.conj().T) 
IAATB = np.matmul(np.eye(n) - AAT, B)
X = np.array([np.linalg.qr(np.matmul(A, X_low[i]) + IAATB)[0] for i in range(N)]) # N x n x p
X = cgr.exp(X, sig * cgr.randvec(X)) # perturb the emdedded X

In [24]:
scores = PNG(X, verbosity = 1)

Gr(1, 12) -> Gr(1, 11)
Terminated - min grad norm reached after 55 iterations, 0.88 seconds.

Gr(1, 11) -> Gr(1, 10)
Terminated - min grad norm reached after 73 iterations, 1.13 seconds.

Gr(1, 10) -> Gr(1, 9)
Terminated - min grad norm reached after 78 iterations, 1.17 seconds.

Gr(1, 9) -> Gr(1, 8)
Terminated - min grad norm reached after 69 iterations, 1.06 seconds.

Gr(1, 8) -> Gr(1, 7)
Terminated - min grad norm reached after 54 iterations, 0.83 seconds.

Gr(1, 7) -> Gr(1, 6)
Terminated - min grad norm reached after 44 iterations, 0.72 seconds.

Gr(1, 6) -> Gr(1, 5)
Terminated - min grad norm reached after 205 iterations, 2.99 seconds.

Gr(1, 5) -> Gr(1, 4)
Terminated - min grad norm reached after 56 iterations, 0.85 seconds.

Gr(1, 4) -> Gr(1, 3)
Terminated - min grad norm reached after 50 iterations, 0.76 seconds.

Gr(1, 3) -> Gr(1, 2)
Terminated - min grad norm reached after 121 iterations, 1.72 seconds.

Gr(1, 2) -> NGM


In [25]:
n_c = 5
cpca = Complex_PCA(n_components = n_c)
cpca.fit(scores_PNG)
print(f'The ratios of expressed variance of the first {n_c} PCs.')
print(cpca.explained_variance_ratio_.round(2))
print(f'The cumulative ratios of expressed variance of the first {n_c} PCs.')
print(np.cumsum(cpca.explained_variance_ratio_).round(2))

The ratios of expressed variance of the first 5 PCs.
[0.5  0.35 0.13 0.02 0.01]
The cumulative ratios of expressed variance of the first 5 PCs.
[0.5  0.85 0.98 0.99 1.  ]


## PGA

In [26]:
N, n, p = X.shape
man = ComplexGrassmann(n, p)
cpga = Complex_PGA(X, n_c, man)
print(f'The ratios of expressed variance of the first {n_c} PCs.')
print(cpga.explained_variance_ratio_.round(2))
print(f'The cumulative ratios of expressed variance of the first {n_c} PCs.')
print(np.cumsum(cpga.explained_variance_ratio_).round(2))

The ratios of expressed variance of the first 5 PCs.
[0.32 0.28 0.23 0.17 0.  ]
The cumulative ratios of expressed variance of the first 5 PCs.
[0.32 0.6  0.83 1.   1.  ]


# Example 3: Supervised Principal Nested Grassmann

## Generate Data

In [22]:
m = 2
n = 5
p = 1
N = 50
n_class = 2
sig = 0.1

gr_low = Grassmann(m, p, N)
y = np.random.randint(n_class, size = N)
M = np.array([[[1],[0]],[[0],[1]]])
X_low = np.zeros((N, m, p))
# translate the X such that different classes are separated
gr = Grassmann(m, p)
for i in range(N):
    X_low[i] = gr.exp(M[y[i]], 0.5 * gr.randvec(M[y[i]]))

gr_map = Grassmann(n, m)
A = gr_map.rand()
#B = np.random.normal(0, 0.1, (n, p)) # n_class x n x p
B = np.zeros((n, p))
AAT = np.matmul(A, A.T) 
IAATB = np.matmul(np.eye(n) - AAT, B)


gr = Grassmann(n, p, N)

X = np.array([np.linalg.qr(np.matmul(A, X_low[i]) + IAATB)[0] for i in range(N)]) # N x n x p
X = gr.exp(X, sig * gr.randvec(X)) # perturb the emdedded X

## Compute the score using SPNG

In [23]:
scores_PNG = SPNG(X, y)

Gr(1, 5) -> Gr(1, 4)
Gr(1, 4) -> Gr(1, 3)
Gr(1, 3) -> Gr(1, 2)
Gr(1, 2) -> NGM


# Example 4: Digit 3 

In [2]:
from shape_transform import *
X = np.load('dataset/digit3.npy')
X = X.transpose((1,2,0))
X = shape_transform(X)

In [6]:
scores_PNG = PNG(X, verbosity = 1)

Gr(1, 12) -> Gr(1, 11)
Terminated - min grad norm reached after 33 iterations, 0.58 seconds.

Gr(1, 11) -> Gr(1, 10)
Terminated - max iterations reached after 14.35 seconds.

Gr(1, 10) -> Gr(1, 9)
Terminated - max iterations reached after 14.80 seconds.

Gr(1, 9) -> Gr(1, 8)
Terminated - max iterations reached after 14.38 seconds.

Gr(1, 8) -> Gr(1, 7)
Terminated - max iterations reached after 14.42 seconds.

Gr(1, 7) -> Gr(1, 6)
Terminated - min grad norm reached after 455 iterations, 6.36 seconds.

Gr(1, 6) -> Gr(1, 5)
Terminated - min grad norm reached after 257 iterations, 3.70 seconds.

Gr(1, 5) -> Gr(1, 4)
Terminated - min grad norm reached after 213 iterations, 3.10 seconds.

Gr(1, 4) -> Gr(1, 3)
Terminated - min grad norm reached after 56 iterations, 0.83 seconds.

Gr(1, 3) -> Gr(1, 2)
Terminated - min grad norm reached after 66 iterations, 0.99 seconds.

Gr(1, 2) -> NGM


In [4]:
n_c = 5
cpca = Complex_PCA(n_components = n_c)
cpca.fit(scores_PNG)
print(f'The ratios of expressed variance of the first {n_c} PCs.')
print(cpca.explained_variance_ratio_.round(2))
print(f'The cumulative ratios of expressed variance of the first {n_c} PCs.')
print(np.cumsum(cpca.explained_variance_ratio_).round(2))

The ratios of expressed variance of the first 5 PCs.
[0.81 0.1  0.06 0.02 0.01]
The cumulative ratios of expressed variance of the first 5 PCs.
[0.81 0.91 0.97 0.99 1.  ]


In [5]:
N, n, p = X.shape
man = ComplexGrassmann(n, p)
cpga = Complex_PGA(X, n_c, man)
print(f'The ratios of expressed variance of the first {n_c} PCs.')
print(cpga.explained_variance_ratio_.round(2))
print(f'The cumulative ratios of expressed variance of the first {n_c} PCs.')
print(np.cumsum(cpga.explained_variance_ratio_).round(2))

The ratios of expressed variance of the first 5 PCs.
[0.61 0.23 0.07 0.03 0.02]
The cumulative ratios of expressed variance of the first 5 PCs.
[0.61 0.84 0.91 0.94 0.96]


# Example 5: Female Gorilla

In [32]:
from shape_transform import *
X = np.load('dataset/gorf.npy')
X = X.transpose((1,2,0))
X = shape_transform(X)

In [36]:
scores_PNG = PNG(X, verbosity = 1)

Gr(1, 7) -> Gr(1, 6)
Terminated - min grad norm reached after 104 iterations, 1.55 seconds.

Gr(1, 6) -> Gr(1, 5)
Terminated - min grad norm reached after 150 iterations, 2.15 seconds.

Gr(1, 5) -> Gr(1, 4)
Terminated - min grad norm reached after 163 iterations, 2.36 seconds.

Gr(1, 4) -> Gr(1, 3)
Terminated - min grad norm reached after 71 iterations, 1.05 seconds.

Gr(1, 3) -> Gr(1, 2)
Terminated - min grad norm reached after 67 iterations, 0.99 seconds.

Gr(1, 2) -> NGM


In [37]:
n_c = 5
cpca = Complex_PCA(n_components = n_c)
cpca.fit(scores_PNG)
print(f'The ratios of expressed variance of the first {n_c} PCs.')
print(cpca.explained_variance_ratio_.round(2))
print(f'The cumulative ratios of expressed variance of the first {n_c} PCs.')
print(np.cumsum(cpca.explained_variance_ratio_).round(2))

The ratios of expressed variance of the first 5 PCs.
[0.62 0.28 0.05 0.03 0.01]
The cumulative ratios of expressed variance of the first 5 PCs.
[0.62 0.9  0.95 0.98 0.99]


In [38]:
N, n, p = X.shape
man = ComplexGrassmann(n, p)
cpga = Complex_PGA(X, n_c, man)
print(f'The ratios of expressed variance of the first {n_c} PCs.')
print(cpga.explained_variance_ratio_.round(2))
print(f'The cumulative ratios of expressed variance of the first {n_c} PCs.')
print(np.cumsum(cpga.explained_variance_ratio_).round(2))

The ratios of expressed variance of the first 5 PCs.
[0.49 0.2  0.13 0.09 0.06]
The cumulative ratios of expressed variance of the first 5 PCs.
[0.49 0.69 0.82 0.91 0.97]
